
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ABSTRACT AND AS ASIGNACION ASIG_CONCA ASIG_REFER BOOLEANO BREAK CADENA CALLABLE CASE CATH CLASS CLONE COMA COMENTARIO CONST CONTINUE CORCH_DER CORCH_IZQ DECLARE DECREMENTO DEFAULT DIFERENTE DIVISION DO ECHO ELSE ELSEIF ENDDECLARE ENDIF ENDSWITCH ENDWHILE ENTERO EXTENDS FINAL FINALLY FLOTANTE FN FOR FOREACH FUNCTION GLOBAL ID IDENTICO IF IGUAL IMPLEMENTS INCLUDE INCREMENTO INTANCEOF INTEADOF INTERFACE INTERROG_CE LLAVE_DER LLAVE_IZQ MACHT MAYOR_IGUAL MAYOR_QUE MENOR_IGUAL MENOR_QUE MODULO MULTIPL NAMESPACE NEW OR PAREN_DER PAREN_IZQ POTENCIA PRINT PRIVATE PROTECTED PUBLIC PUNTO PUNTO_COMA REQUIERE RESTA RETURN SALTO_LINEA SIGNO_DOLAR STATIC STRING SUMA SWITCH TABULACION THROW TRAIT TRY USE VARIABLE WHILE XORsalida : ECHO STRING PUNTO_COMAsalida : PRINT PAREN_IZQ STRING PAREN_DER PUNTO_COMAsalida : PRINT STRING PUNTO_COMAvariable : ASIGNACION ID IGUAL STRING PUNTO_COMA'
    
_lr_action_items = {'ECHO':([0,],[2,]),'PRINT':([0,],[3,]),'$end':([1,7,9,11,],[0,-1,-3,-2,]),'STRING':([2,3,5,],[4,6,8,]),'PAREN_IZQ':([3,],[5,]),'PUNTO_COMA':([4,6,10,],[7,9,11,]),'PAREN_DER':([8,],[10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'salida':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> salida","S'",1,None,None,None),
  ('salida -> ECHO STRING PUNTO_COMA','salida',3,'p_salida_forma1','main.py',11),
  ('salida -> PRINT PAREN_IZQ STRING PAREN_DER PUNTO_COMA','salida',5,'p_salida_forma2','main.py',15),
  ('salida -> PRINT STRING PUNTO_COMA','salida',3,'p_salida_forma3','main.py',19),
  ('variable -> ASIGNACION ID IGUAL STRING PUNTO_COMA','variable',5,'p_variable_ps','main.py',23),
]
